# Generated by Django 2.0.4 on 2018-04-05 00:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("todo", "0006_rename_item_model")]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="created_date",
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        )
    ]
