# Generated by Django 2.2 on 2019-04-23 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def forward_migration(apps, schema_editor):
    BaseTask = apps.get_model("todo", "BaseTask")
    Task = apps.get_model("todo", "Task")
    for base_task in BaseTask.objects.all():
        Task.objects.create(basetask_ptr=base_task)


def backward_migration(apps, schema_editor):
    pass  # fix IrreversibleError


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("todo", "0010_attachment"),
    ]

    operations = [
        migrations.RenameModel("Task", "BaseTask"),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "basetask_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="todo.BaseTask",
                    ),
                )
            ],
        ),
        migrations.RunPython(forward_migration, backward_migration),
        migrations.AlterField(
            model_name="attachment",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.TODO_TASK_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.TODO_TASK_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="basetask_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="todo.BaseTask",
            ),
        ),
    ]
